/**
 * DRIFT FITNESS - EXERCISE LIBRARY (v3.2)
 * Comprehensive 50+ exercise database for production use
 */

import type { Exercise } from "../../types";

export const INITIAL_EXERCISES: Exercise[] = [
  // ============================================================================
  // PUSH - SLOT 1 (Heavy Compounds: 5-8 reps)
  // ============================================================================
  {
    id: "barbell_bench",
    name: "Barbell Bench Press",
    muscleGroup: "push",
    slot: 1,
    type: "compound",
    equipment: "barbell",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "horizontalPush",
  },
  {
    id: "db_bench",
    name: "Dumbbell Bench Press",
    muscleGroup: "push",
    slot: 1,
    type: "compound",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [5, 8],
    movementPattern: "horizontalPush",
  },
  {
    id: "machine_chest_press",
    name: "Machine Chest Press",
    muscleGroup: "push",
    slot: 1,
    type: "compound",
    equipment: "machine",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "horizontalPush",
  },
  {
    id: "barbell_ohp",
    name: "Barbell Overhead Press",
    muscleGroup: "push",
    slot: 1,
    type: "compound",
    equipment: "barbell",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "verticalPush",
  },
  {
    id: "db_shoulder_press",
    name: "Dumbbell Shoulder Press",
    muscleGroup: "push",
    slot: 1,
    type: "compound",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [5, 8],
    movementPattern: "verticalPush",
  },
  {
    id: "weighted_dips",
    name: "Weighted Dips",
    muscleGroup: "push",
    slot: 1,
    type: "compound",
    equipment: "bodyweight",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "verticalPush",
    bodyweightMultiplier: 1.0,
  },
  {
    id: "smith_bench",
    name: "Smith Machine Bench Press",
    muscleGroup: "push",
    slot: 1,
    type: "compound",
    equipment: "smithMachine",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "horizontalPush",
  },

  // ============================================================================
  // PUSH - SLOT 2 (Moderate Compounds: 8-12 reps)
  // ============================================================================
  {
    id: "incline_barbell_press",
    name: "Incline Barbell Press",
    muscleGroup: "push",
    slot: 2,
    type: "compound",
    equipment: "barbell",
    loadType: "bilateral",
    repRange: [8, 12],
    movementPattern: "horizontalPush",
  },
  {
    id: "incline_db_press",
    name: "Incline Dumbbell Press",
    muscleGroup: "push",
    slot: 2,
    type: "compound",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [8, 12],
    movementPattern: "horizontalPush",
  },
  {
    id: "decline_press",
    name: "Decline Barbell Press",
    muscleGroup: "push",
    slot: 2,
    type: "compound",
    equipment: "barbell",
    loadType: "bilateral",
    repRange: [8, 12],
    movementPattern: "horizontalPush",
  },
  {
    id: "cable_press",
    name: "Cable Chest Press",
    muscleGroup: "push",
    slot: 2,
    type: "compound",
    equipment: "cable",
    loadType: "unilateral",
    repRange: [8, 12],
    movementPattern: "horizontalPush",
  },
  {
    id: "machine_shoulder_press",
    name: "Machine Shoulder Press",
    muscleGroup: "push",
    slot: 2,
    type: "compound",
    equipment: "machine",
    loadType: "bilateral",
    repRange: [8, 12],
    movementPattern: "verticalPush",
  },
  {
    id: "landmine_press",
    name: "Landmine Press",
    muscleGroup: "push",
    slot: 2,
    type: "compound",
    equipment: "barbell",
    loadType: "bilateral",
    repRange: [8, 12],
    movementPattern: "verticalPush",
  },

  // ============================================================================
  // PUSH - SLOT 3 (Isolations: 12-15 reps)
  // ============================================================================
  {
    id: "cable_fly",
    name: "Cable Chest Fly",
    muscleGroup: "push",
    slot: 3,
    type: "isolation",
    equipment: "cable",
    loadType: "unilateral",
    repRange: [12, 15],
    primaryMuscle: "chest",
  },
  {
    id: "db_fly",
    name: "Dumbbell Chest Fly",
    muscleGroup: "push",
    slot: 3,
    type: "isolation",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [12, 15],
    primaryMuscle: "chest",
  },
  {
    id: "pec_deck",
    name: "Pec Deck Fly",
    muscleGroup: "push",
    slot: 3,
    type: "isolation",
    equipment: "machine",
    loadType: "bilateral",
    repRange: [12, 15],
    primaryMuscle: "chest",
  },
  {
    id: "lateral_raise",
    name: "Dumbbell Lateral Raise",
    muscleGroup: "push",
    slot: 3,
    type: "isolation",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [12, 15],
    primaryMuscle: "shoulders",
  },
  {
    id: "cable_lateral_raise",
    name: "Cable Lateral Raise",
    muscleGroup: "push",
    slot: 3,
    type: "isolation",
    equipment: "cable",
    loadType: "unilateral",
    repRange: [12, 15],
    primaryMuscle: "shoulders",
  },
  {
    id: "front_raise",
    name: "Dumbbell Front Raise",
    muscleGroup: "push",
    slot: 3,
    type: "isolation",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [12, 15],
    primaryMuscle: "shoulders",
  },
  {
    id: "tricep_pushdown",
    name: "Cable Tricep Pushdown",
    muscleGroup: "push",
    slot: 3,
    type: "isolation",
    equipment: "cable",
    loadType: "bilateral",
    repRange: [12, 15],
    primaryMuscle: "triceps",
  },
  {
    id: "overhead_tricep_ext",
    name: "Overhead Tricep Extension",
    muscleGroup: "push",
    slot: 3,
    type: "isolation",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [12, 15],
    primaryMuscle: "triceps",
  },
  {
    id: "dips_bodyweight",
    name: "Bodyweight Dips",
    muscleGroup: "push",
    slot: 3,
    type: "isolation",
    equipment: "bodyweight",
    loadType: "bilateral",
    repRange: [12, 15],
    primaryMuscle: "triceps",
    bodyweightMultiplier: 1.0,
  },
  {
    id: "pushups",
    name: "Push-ups",
    muscleGroup: "push",
    slot: 3,
    type: "isolation",
    equipment: "bodyweight",
    loadType: "bilateral",
    repRange: [12, 15],
    primaryMuscle: "chest",
    bodyweightMultiplier: 0.65,
  },

  // ============================================================================
  // PULL - SLOT 1 (Heavy Compounds: 5-8 reps)
  // ============================================================================
  {
    id: "barbell_deadlift",
    name: "Barbell Deadlift",
    muscleGroup: "pull",
    slot: 1,
    type: "compound",
    equipment: "barbell",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "hinge",
  },
  {
    id: "barbell_row",
    name: "Barbell Row",
    muscleGroup: "pull",
    slot: 1,
    type: "compound",
    equipment: "barbell",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "horizontalPull",
  },
  {
    id: "weighted_pullup",
    name: "Weighted Pull-up",
    muscleGroup: "pull",
    slot: 1,
    type: "compound",
    equipment: "bodyweight",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "verticalPull",
    bodyweightMultiplier: 1.0,
  },
  {
    id: "weighted_chinup",
    name: "Weighted Chin-up",
    muscleGroup: "pull",
    slot: 1,
    type: "compound",
    equipment: "bodyweight",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "verticalPull",
    bodyweightMultiplier: 1.0,
  },
  {
    id: "tbar_row",
    name: "T-Bar Row",
    muscleGroup: "pull",
    slot: 1,
    type: "compound",
    equipment: "barbell",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "horizontalPull",
  },
  {
    id: "machine_row",
    name: "Machine Row",
    muscleGroup: "pull",
    slot: 1,
    type: "compound",
    equipment: "machine",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "horizontalPull",
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    muscleGroup: "pull",
    slot: 1,
    type: "compound",
    equipment: "cable",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "verticalPull",
  },

  // ============================================================================
  // PULL - SLOT 2 (Moderate Compounds: 8-12 reps)
  // ============================================================================
  {
    id: "db_row",
    name: "Dumbbell Row",
    muscleGroup: "pull",
    slot: 2,
    type: "compound",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [8, 12],
    movementPattern: "horizontalPull",
  },
  {
    id: "cable_row",
    name: "Seated Cable Row",
    muscleGroup: "pull",
    slot: 2,
    type: "compound",
    equipment: "cable",
    loadType: "bilateral",
    repRange: [8, 12],
    movementPattern: "horizontalPull",
  },
  {
    id: "chest_supported_row",
    name: "Chest Supported Row",
    muscleGroup: "pull",
    slot: 2,
    type: "compound",
    equipment: "machine",
    loadType: "bilateral",
    repRange: [8, 12],
    movementPattern: "horizontalPull",
  },
  {
    id: "face_pull",
    name: "Face Pull",
    muscleGroup: "pull",
    slot: 2,
    type: "compound",
    equipment: "cable",
    loadType: "bilateral",
    repRange: [8, 12],
    movementPattern: "horizontalPull",
  },
  {
    id: "pendlay_row",
    name: "Pendlay Row",
    muscleGroup: "pull",
    slot: 2,
    type: "compound",
    equipment: "barbell",
    loadType: "bilateral",
    repRange: [8, 12],
    movementPattern: "horizontalPull",
  },
  {
    id: "underhand_lat_pulldown",
    name: "Underhand Lat Pulldown",
    muscleGroup: "pull",
    slot: 2,
    type: "compound",
    equipment: "cable",
    loadType: "bilateral",
    repRange: [8, 12],
    movementPattern: "verticalPull",
  },

  // ============================================================================
  // PULL - SLOT 3 (Isolations: 12-15 reps)
  // ============================================================================
  {
    id: "barbell_curl",
    name: "Barbell Curl",
    muscleGroup: "pull",
    slot: 3,
    type: "isolation",
    equipment: "barbell",
    loadType: "bilateral",
    repRange: [12, 15],
    primaryMuscle: "biceps",
  },
  {
    id: "db_curl",
    name: "Dumbbell Curl",
    muscleGroup: "pull",
    slot: 3,
    type: "isolation",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [12, 15],
    primaryMuscle: "biceps",
  },
  {
    id: "hammer_curl",
    name: "Hammer Curl",
    muscleGroup: "pull",
    slot: 3,
    type: "isolation",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [12, 15],
    primaryMuscle: "biceps",
  },
  {
    id: "cable_curl",
    name: "Cable Curl",
    muscleGroup: "pull",
    slot: 3,
    type: "isolation",
    equipment: "cable",
    loadType: "bilateral",
    repRange: [12, 15],
    primaryMuscle: "biceps",
  },
  {
    id: "preacher_curl",
    name: "Preacher Curl",
    muscleGroup: "pull",
    slot: 3,
    type: "isolation",
    equipment: "barbell",
    loadType: "bilateral",
    repRange: [12, 15],
    primaryMuscle: "biceps",
  },
  {
    id: "rear_delt_fly",
    name: "Rear Delt Fly",
    muscleGroup: "pull",
    slot: 3,
    type: "isolation",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [12, 15],
    primaryMuscle: "back",
  },
  {
    id: "shrugs",
    name: "Dumbbell Shrugs",
    muscleGroup: "pull",
    slot: 3,
    type: "isolation",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [12, 15],
    primaryMuscle: "back",
  },
  {
    id: "pullups_bodyweight",
    name: "Bodyweight Pull-ups",
    muscleGroup: "pull",
    slot: 3,
    type: "isolation",
    equipment: "bodyweight",
    loadType: "bilateral",
    repRange: [12, 15],
    primaryMuscle: "back",
    bodyweightMultiplier: 1.0,
  },

  // ============================================================================
  // LEGS - SLOT 1 (Heavy Compounds: 5-8 reps)
  // ============================================================================
  {
    id: "back_squat",
    name: "Barbell Back Squat",
    muscleGroup: "legs",
    slot: 1,
    type: "compound",
    equipment: "barbell",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "squat",
  },
  {
    id: "front_squat",
    name: "Barbell Front Squat",
    muscleGroup: "legs",
    slot: 1,
    type: "compound",
    equipment: "barbell",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "squat",
  },
  {
    id: "leg_press",
    name: "Leg Press",
    muscleGroup: "legs",
    slot: 1,
    type: "compound",
    equipment: "machine",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "squat",
  },
  {
    id: "hack_squat",
    name: "Hack Squat",
    muscleGroup: "legs",
    slot: 1,
    type: "compound",
    equipment: "machine",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "squat",
  },
  {
    id: "smith_squat",
    name: "Smith Machine Squat",
    muscleGroup: "legs",
    slot: 1,
    type: "compound",
    equipment: "smithMachine",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "squat",
  },
  {
    id: "romanian_deadlift",
    name: "Romanian Deadlift",
    muscleGroup: "legs",
    slot: 1,
    type: "compound",
    equipment: "barbell",
    loadType: "bilateral",
    repRange: [5, 8],
    movementPattern: "hinge",
  },
  {
    id: "bulgarian_split_squat",
    name: "Bulgarian Split Squat",
    muscleGroup: "legs",
    slot: 1,
    type: "compound",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [5, 8],
    movementPattern: "lunge",
  },

  // ============================================================================
  // LEGS - SLOT 2 (Moderate Compounds: 8-12 reps)
  // ============================================================================
  {
    id: "goblet_squat",
    name: "Goblet Squat",
    muscleGroup: "legs",
    slot: 2,
    type: "compound",
    equipment: "dumbbell",
    loadType: "bilateral",
    repRange: [8, 12],
    movementPattern: "squat",
  },
  {
    id: "db_lunges",
    name: "Dumbbell Lunges",
    muscleGroup: "legs",
    slot: 2,
    type: "compound",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [8, 12],
    movementPattern: "lunge",
  },
  {
    id: "walking_lunges",
    name: "Walking Lunges",
    muscleGroup: "legs",
    slot: 2,
    type: "compound",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [8, 12],
    movementPattern: "lunge",
  },
  {
    id: "barbell_lunges",
    name: "Barbell Lunges",
    muscleGroup: "legs",
    slot: 2,
    type: "compound",
    equipment: "barbell",
    loadType: "bilateral",
    repRange: [8, 12],
    movementPattern: "lunge",
  },
  {
    id: "step_ups",
    name: "Dumbbell Step-ups",
    muscleGroup: "legs",
    slot: 2,
    type: "compound",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [8, 12],
    movementPattern: "lunge",
  },
  {
    id: "db_rdl",
    name: "Dumbbell Romanian Deadlift",
    muscleGroup: "legs",
    slot: 2,
    type: "compound",
    equipment: "dumbbell",
    loadType: "unilateral",
    repRange: [8, 12],
    movementPattern: "hinge",
  },

  // ============================================================================
  // LEGS - SLOT 3 (Isolations: 12-15 reps)
  // ============================================================================
  {
    id: "leg_extension",
    name: "Leg Extension",
    muscleGroup: "legs",
    slot: 3,
    type: "isolation",
    equipment: "machine",
    loadType: "bilateral",
    repRange: [12, 15],
    primaryMuscle: "quads",
  },
  {
    id: "leg_curl",
    name: "Leg Curl",
    muscleGroup: "legs",
    slot: 3,
    type: "isolation",
    equipment: "machine",
    loadType: "bilateral",
    repRange: [12, 15],
    primaryMuscle: "hamstrings",
  },
  {
    id: "seated_leg_curl",
    name: "Seated Leg Curl",
    muscleGroup: "legs",
    slot: 3,
    type: "isolation",
    equipment: "machine",
    loadType: "bilateral",
    repRange: [12, 15],
    primaryMuscle: "hamstrings",
  },
  {
    id: "calf_raise",
    name: "Standing Calf Raise",
    muscleGroup: "legs",
    slot: 3,
    type: "isolation",
    equipment: "machine",
    loadType: "bilateral",
    repRange: [12, 15],
    primaryMuscle: "calves",
  },
  {
    id: "seated_calf_raise",
    name: "Seated Calf Raise",
    muscleGroup: "legs",
    slot: 3,
    type: "isolation",
    equipment: "machine",
    loadType: "bilateral",
    repRange: [12, 15],
    primaryMuscle: "calves",
  },
  {
    id: "hip_thrust",
    name: "Barbell Hip Thrust",
    muscleGroup: "legs",
    slot: 3,
    type: "isolation",
    equipment: "barbell",
    loadType: "bilateral",
    repRange: [12, 15],
    primaryMuscle: "hamstrings",
  },
  {
    id: "glute_bridge",
    name: "Glute Bridge",
    muscleGroup: "legs",
    slot: 3,
    type: "isolation",
    equipment: "bodyweight",
    loadType: "bilateral",
    repRange: [12, 15],
    primaryMuscle: "hamstrings",
    bodyweightMultiplier: 0.75,
  },
  {
    id: "bodyweight_squat",
    name: "Bodyweight Squat",
    muscleGroup: "legs",
    slot: 3,
    type: "isolation",
    equipment: "bodyweight",
    loadType: "bilateral",
    repRange: [12, 15],
    primaryMuscle: "quads",
    bodyweightMultiplier: 0.75,
  },
];

// Validation: Count exercises by muscle group and slot
export const EXERCISE_STATS = {
  total: INITIAL_EXERCISES.length,
  byMuscleGroup: {
    push: INITIAL_EXERCISES.filter((ex) => ex.muscleGroup === "push").length,
    pull: INITIAL_EXERCISES.filter((ex) => ex.muscleGroup === "pull").length,
    legs: INITIAL_EXERCISES.filter((ex) => ex.muscleGroup === "legs").length,
  },
  bySlot: {
    slot1: INITIAL_EXERCISES.filter((ex) => ex.slot === 1).length,
    slot2: INITIAL_EXERCISES.filter((ex) => ex.slot === 2).length,
    slot3: INITIAL_EXERCISES.filter((ex) => ex.slot === 3).length,
  },
  byEquipment: {
    barbell: INITIAL_EXERCISES.filter((ex) => ex.equipment === "barbell").length,
    dumbbell: INITIAL_EXERCISES.filter((ex) => ex.equipment === "dumbbell").length,
    machine: INITIAL_EXERCISES.filter((ex) => ex.equipment === "machine").length,
    cable: INITIAL_EXERCISES.filter((ex) => ex.equipment === "cable").length,
    bodyweight: INITIAL_EXERCISES.filter((ex) => ex.equipment === "bodyweight").length,
    smithMachine: INITIAL_EXERCISES.filter((ex) => ex.equipment === "smithMachine").length,
  },
};
